-- Generated from StatsBomb World Cup 2022 knockout data

DELETE FROM player_match_stats;
DELETE FROM fantasy_team_players;
DELETE FROM matches;
DELETE FROM players;
DELETE FROM fantasy_teams;
DELETE FROM national_teams;
DELETE FROM users;

INSERT INTO national_teams (national_team_id, country, group_name) VALUES (1, 'Argentina', NULL);
INSERT INTO national_teams (national_team_id, country, group_name) VALUES (2, 'Australia', NULL);
INSERT INTO national_teams (national_team_id, country, group_name) VALUES (3, 'Brazil', NULL);
INSERT INTO national_teams (national_team_id, country, group_name) VALUES (4, 'Croatia', NULL);
INSERT INTO national_teams (national_team_id, country, group_name) VALUES (5, 'England', NULL);
INSERT INTO national_teams (national_team_id, country, group_name) VALUES (6, 'France', NULL);
INSERT INTO national_teams (national_team_id, country, group_name) VALUES (7, 'Japan', NULL);
INSERT INTO national_teams (national_team_id, country, group_name) VALUES (8, 'Morocco', NULL);
INSERT INTO national_teams (national_team_id, country, group_name) VALUES (9, 'Netherlands', NULL);
INSERT INTO national_teams (national_team_id, country, group_name) VALUES (10, 'Poland', NULL);
INSERT INTO national_teams (national_team_id, country, group_name) VALUES (11, 'Portugal', NULL);
INSERT INTO national_teams (national_team_id, country, group_name) VALUES (12, 'Senegal', NULL);
INSERT INTO national_teams (national_team_id, country, group_name) VALUES (13, 'South Korea', NULL);
INSERT INTO national_teams (national_team_id, country, group_name) VALUES (14, 'Spain', NULL);
INSERT INTO national_teams (national_team_id, country, group_name) VALUES (15, 'Switzerland', NULL);
INSERT INTO national_teams (national_team_id, country, group_name) VALUES (16, 'United States', NULL);

INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (1, 8, 'Achraf Hakimi Mouh', 'DEF', 7);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (2, 6, 'Adrien Rabiot', 'MID', 8);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (3, 1, 'Alexis Mac Allister', 'MID', 10);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (4, 3, 'Alisson Ramsés Becker', 'GK', 5);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (5, 4, 'Andrej Kramarić', 'FWD', 8);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (6, 9, 'Andries Noppert', 'GK', 5);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (7, 6, 'Antoine Griezmann', 'MID', 8);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (8, 6, 'Aurélien Djani Tchouaméni', 'MID', 9);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (9, 8, 'Azzedine Ounahi', 'MID', 9);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (10, 11, 'Bernardo Mota Veiga de Carvalho e Silva', 'MID', 8);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (11, 4, 'Borna Sosa', 'DEF', 8);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (12, 11, 'Bruno Miguel Borges Fernandes', 'FWD', 7);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (13, 4, 'Bruno Petković', 'FWD', 9);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (14, 5, 'Bukayo Saka', 'FWD', 8);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (15, 3, 'Carlos Henrique Casimiro', 'MID', 9);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (16, 9, 'Cody Mathès Gakpo', 'MID', 10);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (17, 1, 'Cristian Gabriel Romero', 'DEF', 7);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (18, 9, 'Daley Blind', 'DEF', 6);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (19, 1, 'Damián Emiliano Martínez', 'GK', 7);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (20, 3, 'Danilo Luiz da Silva', 'DEF', 7);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (21, 6, 'Dayotchanculle Upamecano', 'DEF', 5);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (22, 5, 'Declan Rice', 'MID', 9);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (23, 4, 'Dejan Lovren', 'DEF', 8);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (24, 9, 'Denzel Dumfries', 'DEF', 6);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (25, 11, 'Diogo Meireles Costa', 'GK', 6);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (26, 4, 'Dominik Livaković', 'GK', 7);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (27, 1, 'Enzo Fernandez', 'MID', 8);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (28, 9, 'Frenkie de Jong', 'MID', 10);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (29, 11, 'Gonçalo Matias Ramos', 'FWD', 8);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (30, 8, 'Hakim Ziyech', 'MID', 8);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (31, 5, 'Harry Kane', 'FWD', 11);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (32, 5, 'Harry Maguire', 'DEF', 8);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (33, 7, 'Hidemasa Morita', 'MID', 8);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (34, 6, 'Hugo Lloris', 'GK', 4);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (35, 4, 'Ivan Perišić', 'FWD', 11);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (36, 8, 'Jawad El Yamiq', 'DEF', 5);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (37, 5, 'John Stones', 'DEF', 5);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (38, 5, 'Jordan Brian Henderson', 'MID', 7);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (39, 5, 'Jordan Pickford', 'GK', 6);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (40, 4, 'Josip Juranović', 'DEF', 5);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (41, 11, 'José Diogo Dalot Teixeira', 'DEF', 8);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (42, 11, 'João Félix Sequeira', 'FWD', 8);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (43, 4, 'Joško Gvardiol', 'DEF', 5);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (44, 5, 'Jude Bellingham', 'MID', 7);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (45, 6, 'Jules Koundé', 'DEF', 5);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (46, 1, 'Julián Álvarez', 'FWD', 8);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (47, 9, 'Jurriën David Norman Timber', 'DEF', 7);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (48, 11, 'Kléper Laveran Lima Ferreira', 'DEF', 5);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (49, 5, 'Kyle Walker', 'DEF', 6);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (50, 6, 'Kylian Mbappé Lottin', 'FWD', 11);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (51, 1, 'Lionel Andrés Messi Cuccittini', 'FWD', 10);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (52, 1, 'Lisandro Martínez', 'MID', 10);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (53, 3, 'Lucas Tolentino Coelho de Lima', 'MID', 7);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (54, 4, 'Luka Modrić', 'MID', 10);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (55, 5, 'Luke Shaw', 'DEF', 7);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (56, 4, 'Marcelo Brozović', 'MID', 7);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (57, 3, 'Marcos Aoás Corrêa', 'DEF', 5);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (58, 1, 'Marcos Javier Acuña', 'DEF', 5);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (59, 4, 'Mario Pašalić', 'FWD', 8);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (60, 4, 'Mateo Kovačić', 'MID', 9);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (61, 9, 'Memphis Depay', 'FWD', 11);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (62, 1, 'Nahuel Molina Lucero', 'DEF', 5);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (63, 9, 'Nathan Aké', 'DEF', 6);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (64, 3, 'Neymar da Silva Santos Junior', 'MID', 7);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (65, 1, 'Nicolás Alejandro Tagliafico', 'DEF', 8);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (66, 1, 'Nicolás Hernán Otamendi', 'DEF', 8);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (67, 8, 'Noussair Mazraoui', 'DEF', 5);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (68, 6, 'Olivier Giroud', 'FWD', 8);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (69, 11, 'Otávio Edmilson da Silva Monteiro', 'MID', 9);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (70, 6, 'Ousmane Dembélé', 'FWD', 7);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (71, 5, 'Philip Foden', 'FWD', 8);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (72, 3, 'Raphael Dias Belloli', 'MID', 8);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (73, 11, 'Raphaël Adelino José Guerreiro', 'DEF', 5);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (74, 6, 'Raphaël Varane', 'DEF', 5);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (75, 3, 'Richarlison de Andrade', 'FWD', 9);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (76, 1, 'Rodrigo Javier De Paul', 'MID', 6);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (77, 8, 'Romain Saïss', 'DEF', 8);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (78, 11, 'Rúben Santos Gato Alves Dias', 'DEF', 8);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (79, 8, 'Selim Amallah', 'MID', 8);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (80, 8, 'Sofiane Boufal', 'MID', 7);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (81, 8, 'Sofyan Amrabat', 'MID', 8);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (82, 6, 'Theo Bernard François Hernández', 'DEF', 5);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (83, 3, 'Thiago Emiliano da Silva', 'DEF', 5);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (84, 3, 'Vinícius José Paixão de Oliveira Júnior', 'MID', 6);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (85, 9, 'Virgil van Dijk', 'DEF', 7);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (86, 8, 'Yahia Attiyat allah', 'DEF', 8);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (87, 8, 'Yassine Bounou', 'GK', 7);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (88, 8, 'Youssef En-Nesyri', 'FWD', 9);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (89, 6, 'Youssouf Fofana', 'MID', 9);
INSERT INTO players (player_id, national_team_id, name, position, price) VALUES (90, 3, 'Éder Gabriel Militão', 'DEF', 8);

INSERT INTO matches (match_id, home_team_id, away_team_id, match_date, home_score, away_score) VALUES (1, 1, 2, '2022-12-03', 2, 1);
INSERT INTO matches (match_id, home_team_id, away_team_id, match_date, home_score, away_score) VALUES (2, 9, 1, '2022-12-09', 2, 2);
INSERT INTO matches (match_id, home_team_id, away_team_id, match_date, home_score, away_score) VALUES (3, 8, 11, '2022-12-10', 1, 0);
INSERT INTO matches (match_id, home_team_id, away_team_id, match_date, home_score, away_score) VALUES (4, 1, 6, '2022-12-18', 3, 3);
INSERT INTO matches (match_id, home_team_id, away_team_id, match_date, home_score, away_score) VALUES (5, 11, 15, '2022-12-06', 6, 1);
INSERT INTO matches (match_id, home_team_id, away_team_id, match_date, home_score, away_score) VALUES (6, 5, 12, '2022-12-04', 3, 0);
INSERT INTO matches (match_id, home_team_id, away_team_id, match_date, home_score, away_score) VALUES (7, 1, 4, '2022-12-13', 3, 0);
INSERT INTO matches (match_id, home_team_id, away_team_id, match_date, home_score, away_score) VALUES (8, 5, 6, '2022-12-10', 1, 2);
INSERT INTO matches (match_id, home_team_id, away_team_id, match_date, home_score, away_score) VALUES (9, 6, 8, '2022-12-14', 2, 0);
INSERT INTO matches (match_id, home_team_id, away_team_id, match_date, home_score, away_score) VALUES (10, 4, 3, '2022-12-09', 1, 1);
INSERT INTO matches (match_id, home_team_id, away_team_id, match_date, home_score, away_score) VALUES (11, 8, 14, '2022-12-06', 0, 0);
INSERT INTO matches (match_id, home_team_id, away_team_id, match_date, home_score, away_score) VALUES (12, 7, 4, '2022-12-05', 1, 1);
INSERT INTO matches (match_id, home_team_id, away_team_id, match_date, home_score, away_score) VALUES (13, 3, 13, '2022-12-05', 4, 1);
INSERT INTO matches (match_id, home_team_id, away_team_id, match_date, home_score, away_score) VALUES (14, 6, 10, '2022-12-04', 3, 1);
INSERT INTO matches (match_id, home_team_id, away_team_id, match_date, home_score, away_score) VALUES (15, 9, 16, '2022-12-03', 3, 1);

INSERT INTO users (user_id, username, email) VALUES
(1, 'westi', 'westi@example.com'),
(2, 'testuser', 'test@example.com');

INSERT INTO fantasy_teams (fantasy_team_id, user_id, team_name, budget) VALUES
(1, 1, 'Westi FC', 100),
(2, 2, 'Test FC', 100);

INSERT INTO fantasy_team_players (fantasy_team_id, player_id) VALUES (1, 1);
INSERT INTO fantasy_team_players (fantasy_team_id, player_id) VALUES (1, 2);
INSERT INTO fantasy_team_players (fantasy_team_id, player_id) VALUES (1, 3);
INSERT INTO fantasy_team_players (fantasy_team_id, player_id) VALUES (1, 4);
INSERT INTO fantasy_team_players (fantasy_team_id, player_id) VALUES (1, 5);
INSERT INTO fantasy_team_players (fantasy_team_id, player_id) VALUES (2, 6);
INSERT INTO fantasy_team_players (fantasy_team_id, player_id) VALUES (2, 7);
INSERT INTO fantasy_team_players (fantasy_team_id, player_id) VALUES (2, 8);
INSERT INTO fantasy_team_players (fantasy_team_id, player_id) VALUES (2, 9);
INSERT INTO fantasy_team_players (fantasy_team_id, player_id) VALUES (2, 10);

INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (1, 51, 1, 1, 0, TRUE, 0, 0, FALSE, 1, 4, 2);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (2, 51, 2, 1, 1, FALSE, 0, 0, FALSE, 0, 2, 2);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (3, 51, 4, 2, 0, FALSE, 0, 0, FALSE, 1, 2, 4);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (4, 51, 7, 1, 1, TRUE, 0, 0, TRUE, 0, 1, 2);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (5, 66, 1, 0, 1, TRUE, 0, 0, FALSE, 0, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (6, 66, 7, 0, 0, TRUE, 0, 0, TRUE, 1, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (7, 27, 1, 0, 0, TRUE, 0, 0, FALSE, 3, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (8, 27, 2, 0, 0, FALSE, 0, 0, FALSE, 0, 2, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (9, 27, 4, 0, 0, FALSE, 0, 0, FALSE, 5, 1, 1);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (10, 27, 7, 0, 0, TRUE, 0, 0, TRUE, 3, 1, 1);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (11, 62, 1, 0, 0, TRUE, 0, 0, FALSE, 1, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (12, 62, 2, 1, 0, FALSE, 0, 0, FALSE, 1, 0, 1);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (13, 62, 7, 0, 0, TRUE, 0, 0, TRUE, 0, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (14, 3, 1, 0, 0, TRUE, 0, 0, FALSE, 1, 1, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (15, 3, 2, 0, 0, FALSE, 0, 0, FALSE, 2, 1, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (16, 3, 4, 0, 1, FALSE, 0, 0, FALSE, 1, 0, 1);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (17, 3, 7, 0, 0, TRUE, 0, 0, TRUE, 1, 2, 1);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (18, 19, 1, 0, 0, TRUE, 1, 0, FALSE, 0, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (19, 19, 2, 0, 0, FALSE, 0, 2, FALSE, 0, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (20, 19, 4, 0, 0, FALSE, 2, 2, FALSE, 0, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (21, 19, 7, 0, 0, TRUE, 2, 0, TRUE, 0, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (22, 17, 1, 0, 0, TRUE, 0, 0, FALSE, 1, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (23, 17, 4, 0, 0, FALSE, 0, 0, FALSE, 1, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (24, 17, 7, 0, 0, TRUE, 0, 0, TRUE, 1, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (25, 76, 1, 0, 0, TRUE, 0, 0, FALSE, 1, 3, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (26, 76, 2, 0, 0, FALSE, 0, 0, FALSE, 1, 1, 1);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (27, 76, 4, 0, 0, FALSE, 0, 0, FALSE, 0, 1, 1);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (28, 76, 7, 0, 0, TRUE, 0, 0, TRUE, 1, 1, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (29, 46, 1, 1, 0, TRUE, 0, 0, FALSE, 2, 0, 1);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (30, 46, 2, 0, 0, FALSE, 0, 0, FALSE, 0, 1, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (31, 46, 4, 0, 0, FALSE, 0, 0, FALSE, 0, 1, 1);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (32, 46, 7, 2, 0, TRUE, 0, 0, TRUE, 0, 0, 2);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (33, 65, 1, 0, 0, TRUE, 0, 0, FALSE, 0, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (34, 65, 4, 0, 0, FALSE, 0, 0, FALSE, 4, 1, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (35, 65, 7, 0, 0, TRUE, 0, 0, TRUE, 0, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (36, 52, 1, 0, 0, TRUE, 0, 0, FALSE, 1, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (37, 52, 2, 0, 0, FALSE, 0, 0, FALSE, 1, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (38, 52, 7, 0, 0, TRUE, 0, 0, TRUE, 1, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (39, 58, 1, 0, 0, TRUE, 0, 0, FALSE, 1, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (40, 58, 2, 0, 0, FALSE, 0, 0, FALSE, 4, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (41, 58, 4, 0, 0, FALSE, 0, 0, FALSE, 1, 2, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (42, 58, 7, 0, 0, TRUE, 0, 0, TRUE, 0, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (43, 16, 2, 0, 0, FALSE, 0, 0, FALSE, 1, 1, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (44, 16, 15, 0, 0, TRUE, 0, 0, FALSE, 2, 4, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (45, 63, 2, 0, 0, FALSE, 0, 0, FALSE, 1, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (46, 63, 15, 0, 0, TRUE, 0, 0, FALSE, 0, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (47, 85, 2, 0, 0, FALSE, 0, 0, FALSE, 1, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (48, 85, 15, 0, 0, TRUE, 0, 0, FALSE, 1, 1, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (49, 28, 15, 0, 0, TRUE, 0, 0, FALSE, 1, 1, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (50, 24, 2, 0, 0, FALSE, 0, 0, FALSE, 2, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (51, 24, 15, 1, 2, TRUE, 0, 0, FALSE, 1, 0, 1);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (52, 6, 2, 0, 0, FALSE, 3, 1, FALSE, 0, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (53, 6, 15, 0, 0, TRUE, 5, 0, FALSE, 0, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (54, 47, 2, 0, 0, FALSE, 0, 0, FALSE, 1, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (55, 47, 15, 0, 0, TRUE, 0, 0, FALSE, 3, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (56, 61, 2, 0, 0, FALSE, 0, 0, FALSE, 0, 1, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (57, 61, 15, 1, 0, TRUE, 0, 0, FALSE, 0, 1, 3);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (58, 18, 2, 0, 0, FALSE, 0, 0, FALSE, 2, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (59, 18, 15, 1, 1, TRUE, 0, 0, FALSE, 4, 0, 1);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (60, 78, 3, 0, 0, FALSE, 0, 0, FALSE, 2, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (61, 78, 5, 0, 0, TRUE, 0, 0, FALSE, 1, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (62, 48, 5, 1, 0, TRUE, 0, 0, FALSE, 0, 0, 1);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (63, 25, 3, 0, 0, FALSE, 2, 0, FALSE, 0, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (64, 25, 5, 0, 0, TRUE, 2, 0, FALSE, 0, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (65, 12, 3, 0, 0, FALSE, 0, 0, FALSE, 1, 3, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (66, 12, 5, 0, 1, TRUE, 0, 0, FALSE, 2, 2, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (67, 10, 3, 0, 0, FALSE, 0, 0, FALSE, 0, 1, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (68, 10, 5, 0, 0, TRUE, 0, 0, FALSE, 0, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (69, 41, 3, 0, 0, FALSE, 0, 0, FALSE, 1, 1, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (70, 41, 5, 0, 0, TRUE, 0, 0, FALSE, 3, 1, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (71, 42, 3, 0, 0, FALSE, 0, 0, FALSE, 0, 0, 2);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (72, 42, 5, 0, 2, TRUE, 0, 0, FALSE, 1, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (73, 69, 3, 0, 0, FALSE, 0, 0, FALSE, 3, 2, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (74, 69, 5, 0, 0, TRUE, 0, 0, FALSE, 1, 1, 1);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (75, 29, 5, 3, 1, TRUE, 0, 0, FALSE, 1, 1, 5);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (76, 73, 3, 0, 0, FALSE, 0, 0, FALSE, 1, 1, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (77, 73, 5, 1, 1, TRUE, 0, 0, FALSE, 0, 1, 1);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (78, 81, 3, 0, 0, TRUE, 0, 0, TRUE, 3, 1, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (79, 81, 9, 0, 0, FALSE, 0, 0, FALSE, 2, 1, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (80, 81, 11, 0, 0, FALSE, 0, 0, TRUE, 3, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (81, 9, 3, 0, 0, TRUE, 0, 0, TRUE, 0, 2, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (82, 9, 9, 0, 0, FALSE, 0, 0, FALSE, 0, 0, 1);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (83, 9, 11, 0, 0, FALSE, 0, 0, TRUE, 2, 1, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (84, 1, 3, 0, 0, TRUE, 0, 0, TRUE, 1, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (85, 1, 9, 0, 0, FALSE, 0, 0, FALSE, 2, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (86, 1, 11, 0, 0, FALSE, 0, 0, TRUE, 3, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (87, 87, 3, 0, 0, TRUE, 3, 0, TRUE, 0, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (88, 87, 11, 0, 0, FALSE, 1, 3, TRUE, 0, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (89, 30, 3, 0, 0, TRUE, 0, 0, TRUE, 0, 2, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (90, 30, 11, 0, 0, FALSE, 0, 0, TRUE, 0, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (91, 80, 3, 0, 0, TRUE, 0, 0, TRUE, 0, 0, 1);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (92, 80, 9, 0, 0, FALSE, 0, 0, FALSE, 1, 1, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (93, 80, 11, 0, 0, FALSE, 0, 0, TRUE, 2, 1, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (94, 88, 3, 1, 0, TRUE, 0, 0, TRUE, 1, 1, 1);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (95, 88, 11, 0, 0, FALSE, 0, 0, TRUE, 0, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (96, 77, 3, 0, 0, TRUE, 0, 0, TRUE, 0, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (97, 77, 11, 0, 0, FALSE, 0, 0, TRUE, 1, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (98, 79, 3, 0, 0, TRUE, 0, 0, TRUE, 1, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (99, 79, 9, 0, 0, FALSE, 0, 0, FALSE, 3, 1, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (100, 79, 11, 0, 0, FALSE, 0, 0, TRUE, 0, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (101, 36, 3, 0, 0, TRUE, 0, 0, TRUE, 1, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (102, 36, 9, 0, 0, FALSE, 0, 0, FALSE, 0, 0, 1);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (103, 36, 11, 0, 0, FALSE, 0, 0, TRUE, 0, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (104, 86, 3, 0, 1, TRUE, 0, 0, TRUE, 1, 1, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (105, 86, 9, 0, 0, FALSE, 0, 0, FALSE, 1, 1, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (106, 86, 11, 0, 0, FALSE, 0, 0, TRUE, 1, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (107, 67, 3, 0, 0, TRUE, 0, 0, TRUE, 0, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (108, 67, 9, 0, 0, FALSE, 0, 0, FALSE, 1, 1, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (109, 67, 11, 0, 0, FALSE, 0, 0, TRUE, 3, 0, 1);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (110, 45, 4, 0, 0, FALSE, 0, 0, FALSE, 3, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (111, 45, 8, 0, 0, TRUE, 0, 0, FALSE, 0, 1, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (112, 45, 9, 0, 0, TRUE, 0, 0, TRUE, 1, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (113, 45, 14, 0, 0, TRUE, 0, 0, FALSE, 2, 1, 1);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (114, 74, 8, 0, 0, TRUE, 0, 0, FALSE, 0, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (115, 74, 9, 0, 0, TRUE, 0, 0, TRUE, 1, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (116, 74, 14, 0, 0, TRUE, 0, 0, FALSE, 0, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (117, 34, 4, 0, 0, FALSE, 7, 0, FALSE, 0, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (118, 34, 8, 0, 0, TRUE, 6, 0, FALSE, 0, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (119, 34, 9, 0, 0, TRUE, 1, 0, TRUE, 0, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (120, 34, 14, 0, 0, TRUE, 1, 0, FALSE, 0, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (121, 50, 4, 3, 0, FALSE, 0, 0, FALSE, 0, 0, 3);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (122, 50, 8, 0, 0, TRUE, 0, 0, FALSE, 0, 1, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (123, 50, 9, 0, 0, TRUE, 0, 0, TRUE, 0, 2, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (124, 50, 14, 2, 1, TRUE, 0, 0, FALSE, 0, 1, 3);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (125, 7, 4, 0, 0, FALSE, 0, 0, FALSE, 1, 1, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (126, 7, 8, 0, 2, TRUE, 0, 0, FALSE, 1, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (127, 7, 9, 0, 0, TRUE, 0, 0, TRUE, 1, 4, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (128, 7, 14, 0, 0, TRUE, 0, 0, FALSE, 0, 3, 1);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (129, 82, 8, 0, 0, TRUE, 0, 0, FALSE, 2, 2, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (130, 82, 9, 1, 0, TRUE, 0, 0, TRUE, 4, 0, 1);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (131, 82, 14, 0, 0, TRUE, 0, 0, FALSE, 1, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (132, 8, 4, 0, 0, FALSE, 0, 0, FALSE, 1, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (133, 8, 8, 1, 0, TRUE, 0, 0, FALSE, 0, 0, 1);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (134, 8, 9, 0, 0, TRUE, 0, 0, TRUE, 1, 2, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (135, 8, 14, 0, 0, TRUE, 0, 0, FALSE, 0, 1, 1);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (136, 2, 4, 0, 0, FALSE, 0, 0, FALSE, 0, 0, 1);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (137, 2, 8, 0, 0, TRUE, 0, 0, FALSE, 1, 0, 1);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (138, 2, 9, 0, 0, TRUE, 0, 0, TRUE, 0, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (139, 2, 14, 0, 0, TRUE, 0, 0, FALSE, 1, 1, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (140, 70, 8, 0, 0, TRUE, 0, 0, FALSE, 1, 2, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (141, 70, 9, 0, 0, TRUE, 0, 0, TRUE, 1, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (142, 70, 14, 0, 1, TRUE, 0, 0, FALSE, 0, 1, 1);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (143, 68, 8, 1, 0, TRUE, 0, 0, FALSE, 0, 0, 3);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (144, 68, 9, 0, 0, TRUE, 0, 0, TRUE, 0, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (145, 68, 14, 1, 0, TRUE, 0, 0, FALSE, 0, 0, 1);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (146, 21, 4, 0, 0, FALSE, 0, 0, FALSE, 1, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (147, 21, 8, 0, 0, TRUE, 0, 0, FALSE, 0, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (148, 21, 9, 0, 0, TRUE, 0, 0, TRUE, 0, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (149, 21, 14, 0, 0, TRUE, 0, 0, FALSE, 2, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (150, 89, 8, 0, 0, TRUE, 0, 0, FALSE, 0, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (151, 89, 9, 0, 0, TRUE, 0, 0, TRUE, 3, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (152, 89, 14, 0, 0, TRUE, 0, 0, FALSE, 1, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (153, 22, 6, 0, 0, TRUE, 0, 0, TRUE, 1, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (154, 22, 8, 0, 0, FALSE, 0, 0, FALSE, 1, 1, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (155, 49, 6, 0, 0, TRUE, 0, 0, TRUE, 0, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (156, 49, 8, 0, 0, FALSE, 0, 0, FALSE, 1, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (157, 32, 6, 0, 0, TRUE, 0, 0, TRUE, 2, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (158, 32, 8, 0, 0, FALSE, 0, 0, FALSE, 1, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (159, 55, 6, 0, 0, TRUE, 0, 0, TRUE, 1, 2, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (160, 55, 8, 0, 0, FALSE, 0, 0, FALSE, 1, 1, 1);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (161, 39, 6, 0, 0, TRUE, 1, 0, TRUE, 0, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (162, 39, 8, 0, 0, FALSE, 3, 0, FALSE, 0, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (163, 31, 6, 1, 0, TRUE, 0, 0, TRUE, 0, 1, 2);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (164, 31, 8, 1, 0, FALSE, 0, 0, FALSE, 0, 0, 4);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (165, 44, 6, 0, 1, TRUE, 0, 0, TRUE, 2, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (166, 44, 8, 0, 0, FALSE, 0, 0, FALSE, 1, 1, 1);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (167, 37, 6, 0, 0, TRUE, 0, 0, TRUE, 0, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (168, 37, 8, 0, 0, FALSE, 0, 0, FALSE, 1, 1, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (169, 38, 6, 1, 0, TRUE, 0, 0, TRUE, 2, 0, 1);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (170, 38, 8, 0, 0, FALSE, 0, 0, FALSE, 0, 3, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (171, 71, 6, 0, 1, TRUE, 0, 0, TRUE, 1, 1, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (172, 71, 8, 0, 0, FALSE, 0, 0, FALSE, 0, 2, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (173, 14, 6, 1, 0, TRUE, 0, 0, TRUE, 2, 1, 1);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (174, 14, 8, 0, 0, FALSE, 0, 0, FALSE, 2, 2, 1);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (175, 35, 7, 0, 0, FALSE, 0, 0, FALSE, 1, 1, 1);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (176, 35, 10, 0, 0, FALSE, 0, 0, FALSE, 1, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (177, 35, 12, 1, 0, FALSE, 0, 0, FALSE, 1, 1, 2);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (178, 60, 7, 0, 0, FALSE, 0, 0, FALSE, 2, 3, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (179, 60, 10, 0, 0, FALSE, 0, 0, FALSE, 4, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (180, 60, 12, 0, 0, FALSE, 0, 0, FALSE, 3, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (181, 54, 7, 0, 0, FALSE, 0, 0, FALSE, 1, 2, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (182, 54, 10, 0, 0, FALSE, 0, 0, FALSE, 2, 1, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (183, 54, 12, 0, 0, FALSE, 0, 0, FALSE, 1, 0, 1);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (184, 23, 7, 0, 0, FALSE, 0, 0, FALSE, 1, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (185, 23, 10, 0, 0, FALSE, 0, 0, FALSE, 1, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (186, 23, 12, 0, 1, FALSE, 0, 0, FALSE, 0, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (187, 26, 7, 0, 0, FALSE, 4, 0, FALSE, 0, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (188, 26, 10, 0, 0, FALSE, 10, 2, FALSE, 0, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (189, 26, 12, 0, 0, FALSE, 3, 3, FALSE, 0, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (190, 40, 7, 0, 0, FALSE, 0, 0, FALSE, 3, 1, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (191, 40, 10, 0, 0, FALSE, 0, 0, FALSE, 3, 3, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (192, 40, 12, 0, 0, FALSE, 0, 0, FALSE, 0, 2, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (193, 43, 7, 0, 0, FALSE, 0, 0, FALSE, 4, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (194, 43, 10, 0, 0, FALSE, 0, 0, FALSE, 1, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (195, 43, 12, 0, 0, FALSE, 0, 0, FALSE, 2, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (196, 56, 7, 0, 0, FALSE, 0, 0, FALSE, 1, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (197, 56, 10, 0, 0, FALSE, 0, 0, FALSE, 2, 1, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (198, 56, 12, 0, 0, FALSE, 0, 0, FALSE, 0, 4, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (199, 5, 7, 0, 0, FALSE, 0, 0, FALSE, 0, 2, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (200, 5, 12, 0, 0, FALSE, 0, 0, FALSE, 1, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (201, 11, 10, 0, 0, FALSE, 0, 0, FALSE, 1, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (202, 59, 7, 0, 0, FALSE, 0, 0, FALSE, 1, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (203, 59, 10, 0, 0, FALSE, 0, 0, FALSE, 3, 1, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (204, 13, 10, 1, 0, FALSE, 0, 0, FALSE, 1, 2, 1);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (205, 13, 12, 0, 0, FALSE, 0, 0, FALSE, 2, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (206, 53, 10, 0, 1, FALSE, 0, 0, FALSE, 1, 0, 2);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (207, 53, 13, 1, 0, TRUE, 0, 0, FALSE, 2, 3, 2);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (208, 20, 13, 0, 0, TRUE, 0, 0, FALSE, 1, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (209, 90, 10, 0, 0, FALSE, 0, 0, FALSE, 3, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (210, 90, 13, 0, 0, TRUE, 0, 0, FALSE, 3, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (211, 83, 10, 0, 0, FALSE, 0, 0, FALSE, 2, 2, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (212, 83, 13, 0, 1, TRUE, 0, 0, FALSE, 1, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (213, 57, 10, 0, 0, FALSE, 0, 0, FALSE, 0, 1, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (214, 57, 13, 0, 0, TRUE, 0, 0, FALSE, 0, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (215, 15, 10, 0, 0, FALSE, 0, 0, FALSE, 2, 3, 1);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (216, 15, 13, 0, 0, TRUE, 0, 0, FALSE, 2, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (217, 75, 10, 0, 0, FALSE, 0, 0, FALSE, 1, 4, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (218, 75, 13, 1, 0, TRUE, 0, 0, FALSE, 1, 1, 2);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (219, 64, 10, 1, 0, FALSE, 0, 0, FALSE, 0, 1, 5);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (220, 64, 13, 1, 0, TRUE, 0, 0, FALSE, 0, 1, 1);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (221, 4, 13, 0, 0, TRUE, 5, 0, FALSE, 0, 0, 0);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (222, 72, 13, 0, 0, TRUE, 0, 0, FALSE, 2, 3, 3);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (223, 84, 10, 0, 0, FALSE, 0, 0, FALSE, 1, 0, 1);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (224, 84, 13, 1, 1, TRUE, 0, 0, FALSE, 0, 1, 1);
INSERT INTO player_match_stats (stat_id, player_id, match_id, goals, assists, country_won, saves, penalty_saves, clean_sheet, successful_tackles, key_passes, shots_on_target) VALUES (225, 33, 12, 0, 0, FALSE, 0, 0, FALSE, 0, 1, 0);